### ISSUE TITLE
Event detection threshold default values

### ISSUE THREAD

**Issue by hiruna72** [haowenz/sigmap#13]
Hi @haowenz,

Thank you for the very useful tool. 
I can see that the default threshold values for the event detection parameters (DNA) used in Sigmap are different from Scrappie. 

```
Sigmap
   threshold1 = 4.30265f
   threshold2 = 2.57058f
Scrappie
   threshold1 = 1.4f,
   threshold2 = 9.0f,

```

Could you please share the motives for the choice of new values?

Thank you.
Regards,
Hiruna

**Comment by haowenz** [comment]
I cannot remember exactly. But if you look at the [table](https://en.wikibooks.org/wiki/Engineering_Tables/Student%27s_T-Distribution), you would find they are 97.5% confidence limit for 2 and 5 degrees of freedom. And the window sizes for the t-tests are 3 and 6. I guess that might be the reason.

**Comment by hiruna72** [comment]
Thank you @haowenz. That makes sense.

**Comment by hiruna72** [comment]
Hello @haowenz,

I see that the t-statistic approach you have used in the program undersegments the signal, i.e., the number of events it gives is nearly the half the number of bases (when compared with the basecalled read). 

Is this the intended behaviour?

**Comment by haowenz** [comment]
I think so. But I cannot remember the exact reason. I guess it was because there were so many stay errors using the default parameters. And the method we proposed is more robust to skip errors rather than stay errors.

I think the high level idea is that merging some events with similar current values is fine as it is hard to distinguish them. And the good thing that is that after this "merging", the seed hits will still be there. But if you have stay errors, the seed hits are gone.

**Comment by hiruna72** [comment]
Thank you @haowenz. That is very intuitive.
